### ISSUE TITLE
BUG with timer history

### ISSUE THREAD

**Issue by OwenQian** [danenespoli/watch#20] opened 2017-03-27 01:30 UTC
When your timer history overflows and starts scrolling, moving your mouse in that sidebar snaps the history back to the bottom, making it impossible to click the clear all trash con button

**Comment by danenespoli** [comment] 2017-03-27 16:44
Duplicate of #8 I believe. Fixed but not yet deployed. Thanks Owen!

**Closed as completed by danenespoli** 2017-03-27 16:44 UTC
